name: Discord
on:
  - push

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Discord Webhook
        uses: Sniddl/discord-cornits@v1.6
        with:
          webhook: ${[ secrets.DISCORD _NEBHOOK 3)
          template: "avatar-with-1ink"
          include-extras: true